packages:
  - apps/*
  - packages/*

catalog:
  '@ant-design/icons': ^6
  '@rsbuild/core': ~1.7.2
  '@rsbuild/plugin-less': ~1.5.1
  '@rsbuild/plugin-react': ~1.4.3
  '@types/node': ^24.10.9
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  antd: ^6.2.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-icons: ^5.5.0
  react-router: ^7.12.0
  typescript: ~5.9.3
  valtio: ~2.3.0
